apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "tile38.fullname" . }}-leader
  labels:
    app: {{ template "tile38.name" . }}
    chart: {{ template "tile38.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: leader
spec:
  serviceName: {{ template "tile38.fullname" . }}-leader
  replicas: {{ .Values.leader.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "tile38.name" . }}
      release: {{ .Release.Name }}
      role: leader
  template:
    metadata:
      labels:
        app: {{ template "tile38.name" . }}
        release: {{ .Release.Name }}
        role: leader
    spec:
      containers:
        - name: {{ .Chart.Name }}-leader
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: "{{ .Values.leader.persistentVolume.mountPath }}"
              subPath: "{{ .Values.leader.persistentVolume.subPath }}"
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          resources:
{{ toYaml .Values.leader.resources | indent 12 }}
    {{- with .Values.leader.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.leader.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.leader.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
  {{- if .Values.leader.persistentVolume.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
        {{- if .Values.leader.persistentVolume.annotations }}
        annotations:
{{ toYaml .Values.leader.persistentVolume.annotations | indent 10 }}
        {{- end }}
      spec:
        accessModes:
{{ toYaml .Values.leader.persistentVolume.accessModes | indent 10 }}
        resources:
          requests:
            storage: {{ .Values.leader.persistentVolume.size | quote }}
      {{- if .Values.leader.persistentVolume.storageClass }}
        storageClassName: {{ .Values.leader.persistentVolume.storageClass | quote }}
      {{- end }}
  {{- else }}
      volumes:
        - name: data
          emptyDir: {}
  {{- end }}
